apiVersion: v1
kind: DeploymentConfig
metadata:
  name: dc
spec:
  replicas: 2
  selector:
    app: santander-phpinfo
  template:
    metadata:
      labels:
        app: santander-phpinfo
    spec:
      containers:
        -
          args:
            - -f
            - index.php
            - -S
            - 0.0.0.0:8080
          command:
            - php
          name: php
          image: ganimedescolomar/santander-phpinfo
          ports:
            -
              containerPort: 8080
              protocol: TCP
          
          env:
            -
              name: nombre_alumno
              value: gani
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      imagePullSecrets: docker-login
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status: {}  
