apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  replicas: 2
  selector:
    app: santander-phpinfo
  template:
    metadata:
      labels:
        app: santander-phpinfo
    spec:
      containers:
        - name: php
          image: ganimedescolomar/santander-phpinfo
          ports:
            - containerPort: 8080
