name: ci
on:
  push:
    branches:
      -
        docker-s
jobs:
  Dockerfile:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: docker build
        run: docker build -t santander-phpinfo:test -f Dockerfile ./
      -
        name: docker run
        run: docker run -d --name santander-phpinfo -v $PWD/src/:/app/ --entrypoint php santander-phpinfo:test -f index.php -S 0.0.0.0:8080
      -
        name: docker logs
        run: |
            while true; do
                    sleep 10;
                    docker logs santander-phpinfo 2>& 1 | grep 'PHP .* Development Server .* started' && break
            done;
